### ISSUE TITLE
integer division or modulo by zero

### ISSUE THREAD

**Issue by 1875434541** [icon-lab/ResViT#22]
I encountered no issues during the pre-training of ART blocks without the presence of transformers for one-to-one tasks with the following command:

```bash
python3 train.py --dataroot /home/sealwang/Downloads/T1__T2 --name T1_T2_Brats18_pre_trained --gpu_ids 0 --model resvit_one --which_model_netG res_cnn --which_direction AtoB --lambda_A 100 --dataset_mode aligned --norm batch --pool_size 0 --output_nc 1 --input_nc 1 --loadSize 240 --fineSize 240 --niter 50 --niter_decay 50 --save_epoch_freq 5 --checkpoints_dir ./checkpoints --display_id 0 --lr 0.0002
```

However, I ran into a problem during the fine-tuning phase of ResViT for one-to-one tasks with the following command:

```bash
python3 train.py --dataroot /home/sealwang/Downloads/T1__T2 --name T1_T2_Brats18_resvit --gpu_ids 0 --model resvit_one --which_model_netG resvit --which_direction AtoB --lambda_A 100 --dataset_mode aligned --norm batch --pool_size 0 --output_nc 1 --input_nc 1 --loadSize 240 --fineSize 240 --niter 25 --niter_decay 25 --save_epoch_freq 5 --checkpoints_dir ./checkpoints --display_id 0 --pre_trained_transformer 1 --pre_trained_resnet 1 --pre_trained_path ./checkpoints/T1_T2_Brats18_pre_trained/latest_net_G.pth --lr 0.001
```

The issue encountered was a `ZeroDivisionError` during the initialization of the model. Here is the traceback for reference:

```
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    model = create_model(opt)
  File "/home/sealwang/Documents/ResViT-main from skarea/models/__init__.py", line 16, in create_model
    model.initialize(opt)
  File "/home/sealwang/Documents/ResViT-main from skarea/models/resvit_one.py", line 19, in initialize
    self.netG = networks.define_G(opt.input_nc, opt.output_nc, opt.ngf,
  File "/home/sealwang/Documents/ResViT-main from skarea/models/networks.py", line 122, in define_G
    netG = residual_transformers.ResViT(residual_transformers.CONFIGS[vit_name],input_dim = input_nc,img_size=img_size, output_dim=1, vis=False)
  File "/home/sealwang/Documents/ResViT-main from skarea/models/residual_transformers.py", line 387, in __init__
    self.art_1 = ART_block(self.config, input_dim, img_size,transformer = self.transformer_encoder)
  File "/home/sealwang/Documents/ResViT-main from skarea/models/residual_transformers.py", line 299, in __init__
    self.embeddings = Embeddings(config, img_size=img_size, input_dim=input_dim)
  File "/home/sealwang/Documents/ResViT-main from skarea/models/residual_transformers.py", line 124, in __init__
    n_patches = (img_size[0] // patch_size_real[0]) * (img_size[1] // patch_size_real[1])
ZeroDivisionError: integer division or modulo by zero
(.env) sealwang@sealwang:~/Documents/ResViT-main from skarea$
```

It appears that the issue arises during the initialization of the `Embeddings` class in the `residual_transformers.py` file, specifically when calculating `n_patches` from `img_size` and `patch_size_real`. This results in a division by zero error.

I would greatly appreciate any guidance or suggestions on how to resolve this issue.

**Comment by 1875434541** [comment]
solved
